### PR TITLE
This method allows you to re-define a parameter that had already been defined beforehand.

### PR DESCRIPTION
**Pull request by YvanGuifo**
Merge e364d0ffecb4aafcd471321712efc0aa9545efe7

### CODE REVIEW

**Comment by SergeStinckwich** [comment]
I don't see the point of this method. Does it fix a fix (and then link to the issue), is there a specific need for that (and then wrote a test to illustrate the need) or do it simplify the code in any way?

**Comment by YvanGuifo** [comment]
We saw that when we define a parameter in a concern and a new concern pation pation pation made a copy of the old one by re-defining a parameter of the old concern, it is important to define a changeParameter method

**Comment by YvanGuifo** [comment]
We saw that when we define a parameter in a concern and a new concern made a copy of the old one by re-defining a parameter of the old concern, it is important to define a changeParameter method.
Example :
```Smalltalk
sirStroudConcernPowerLawWithRungeKutta
	| sirConcern model stroudConcern powerLawConcern simulator dB |
	
	model := KEModel new.

	sirConcern := KEModelPart new.
	sirConcern attributes: 
		{#status->#(#S #I #R)}.
	sirConcern addParameters: {#lambda. #gamma}.
	 
	sirConcern
		addTransitionFrom: {(#status -> #S)}
		to: {(#status -> #I)}
		probability: 'lambda'.
	
	sirConcern
		addTransitionFrom: {(#status -> #I)} 
		to: {(#status -> #R)}
		probability: 'gamma'.
		
	stroudConcern := sirConcern copy.
	stroudConcern addParameters: {#tau. #R0}.
	stroudConcern addParameter: #alpha value: '(R0/tau)'.
	stroudConcern changeParameter: #lambda value: '(alpha*I/N)'.
	stroudConcern changeParameter: #gamma value: '(1/tau)'.
	
	powerLawConcern := stroudConcern copy.
	powerLawConcern addParameter: #puissance value: '(S/N)^power'.
	powerLawConcern changeParameter: #lambda value: '(alpha * I * puissance)/S'.

		
	model integrate: sirConcern.
	model integrate: stroudConcern.
	model integrate: powerLawConcern.
	
	model
		addParameters:
			{
			 (#R0 -> 1.34).
			 (#tau -> 4.1).
			 (#power -> 2.06)}.
	
	model atCompartment: {(#status -> #S)} put: 16106323 atOthersPut: 0.
	model atCompartment: {(#status -> #I)} put: 202.
	
	simulator := KESimulator
		new: #RungeKutta
		from: 0.0
		to: 250
		step: 0.1.
	simulator executeOn: model.
	dB := KEDiagramBuilder new.
	
	dB addData: (simulator timeSeriesOutputsAt: {(#status -> #I)})/5.
											     
	dB  xLabel: 'Time (days)'.
	dB  yLabel: '(New infections per day)'.
	dB legendTitle: 'SIRPowerLawConcern Compartmental model with RungeKutta'.
	dB open

```

**Comment by SergeStinckwich** [comment]
Linked to #128

**Review by SergeStinckwich — APPROVED** [review]

**Pull request merged**
